### ISSUE TITLE
Shazify isn't updating past XXX/YYY

### ISSUE THREAD

**Issue by nicobdx** [leeroybrun/chrome-shazify#23]
I was so happy to find this extension as I have 1000+ tags on shazam and wanted to import them on spotify! I started the update process and for some reason it stopped at 371/1099 due a my internet crashing!
I cant get it back up and running, its still blocked!
please help, this extension is too awesome to abandon!

**Comment by leeroybrun** [comment]
Thanks for your feedback.

Can you try to go in Shazify, in the settings (gear icon on top right), then advanced settings and "Remove all data".

This will remove the data stored in Shazify and start again.

It will start the sync from the begining and maybe this time it will works.

If it does not works, you can "Export the logs" from the advanced settings too, and post it here so I can have a look.

Thanks!

**Comment by nicobdx** [comment]
Thanks for your reply.

Unfortunately I cannot do that as Shazify is still searching for tracks and therefore I cant click on anything, theupdate overlaying the rest of the app. 
Similarly I can't export the logs and the update is overlaying the app.

I tried uninstalling/reinstalling, deleting accesses, everthing I can think of and it just doesn't work. I don't understand why.

**Comment by nicobdx** [comment]
Still impossible to do anything.
Moreover, for the songs that it had identified, none of them appear in spotify.

**Comment by leeroybrun** [comment]
Sorry for the delay.

I thought of a solution, now I just need to implement it.

I will try to do this as soon as possible.

**Comment by leeroybrun** [comment]
I check the source code, but I can't tell where the problem is.
It should never stay blocked on the "updating" overlay...

I just pushed a new version to the Chrome webstore that should let you see the logs even in the update overlay. 

It can take a while before being updated in our browser, so in the meanwhile can you please do the following to export the logs:

Go to the list of your Chrome extensions (copy-paste this URL in your browser: [chrome://extensions/](chrome://extensions/)).

Then search for Shazify, you should have a link "Inspect view : background page" (something like that, my Chrome is in french and shows "Examiner les vues : page en arrière plan") :
<img width="750" alt="capture d ecran 2018-03-11 a 14 58 20" src="https://user-images.githubusercontent.com/1729528/37254370-e282c836-253c-11e8-8729-89ea556117c6.png">

This will open the Chrome Devtools of the Shazify core. 

Go to the "Console" tab, copy everything and paste it here so I can see where the problem is.

Thanks!

**Comment by nicobdx** [comment]
I updated to the most recent version of Chrome (65.0.3325.146 (Build officiel) (64 bits)), updated to the latest version of Shazify, and it still blocks at around 344/1072.
![image](https://user-images.githubusercontent.com/36456215/37254962-f5ba2378-2545-11e8-83f9-5c28077e9225.png)

I can't find the "inspect view: background page" you are refering to (my chrome is in french as well).
![image](https://user-images.githubusercontent.com/36456215/37254972-1b257be4-2546-11e8-98ad-acd0cbf2a635.png)

And when I click on the shazify extensions/settings, I can't access to to logs or anything as the overlay with the update is still present.
![image](https://user-images.githubusercontent.com/36456215/37254992-48ad8610-2546-11e8-89b2-a064bf844928.png)

**Comment by leeroybrun** [comment]
Je te propose qu'on continue en français alors. :-)

Est-ce que tu as quelque part un endroit pour activer le "Mode développeur" dans la vue des extensions dans Chrome? Chez moi c'est tout en haut de la liste des extensions.

Je pense que "Examiner les vues" ne s'affiche pas sinon.

<img width="769" alt="capture d ecran 2018-03-11 a 16 35 25" src="https://user-images.githubusercontent.com/1729528/37255286-7164b624-254a-11e8-9224-22bdf4796762.png">

**Comment by nicobdx** [comment]
![image](https://user-images.githubusercontent.com/36456215/37255998-07639ed8-2555-11e8-9aa9-4d4d49d61790.png)
 
![image](https://user-images.githubusercontent.com/36456215/37256008-231665c0-2555-11e8-877a-33c919272a24.png)

**Comment by leeroybrun** [comment]
Parfait, merci!

Je viens de corriger les deux erreurs et de publier une nouvelle version (0.4.6).

Une fois qu'il se mettra à jour chez toi, pourras-tu m'indiquer si ça fonctionne cette fois?
